---
- name: Installer k3s, k3d et Argo CD
  hosts: all
  become: yes
  tasks:
    - name: Installer k3s
      shell: curl -sfL https://get.k3s.io | sh -

    - name: Installer k3d
      shell: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

    - name: Installer kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        rm -f kubectl

    - name: Créer le namespace Argo CD
      shell: kubectl create namespace argocd || true

    - name: Installer Argo CD
      shell: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

