- hosts: masters
  become: yes
  tasks:
    - name: Installer dépendances
      apt:
        name:
          - curl
        state: present
        update_cache: yes

    - name: Installer k3s (server)
      shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110" sh - 
      args:
        creates: /usr/local/bin/k3s

    - name: Vérifier que k3s est lancé
      systemd:
        name: k3s
        state: started
        enabled: yes
