Vagrant.configure("2") do |config|

    config.vm.define "ahors" do |master|
        master.vm.box = "debian/bullseye64"
        master.vm.network "private_network", ip: "192.168.56.110"
        master.vm.hostname = "ahorsS"

        master.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "1"
            vb.name = "ahorsS"
        end

        master.vm.provision "shell", inline: <<-SHELL
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install ansible==8.7.0
        SHELL

        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "install-k3s.yml"
            ansible.inventory_path = "inventory.ini"
        end
    end
end
