Vagrant.configure("2") do |config|

    config.vm.define "ahors" do |master|
        master.vm.box = "debian/bullseye64"
        master.vm.network "private_network", ip: "192.168.56.110"
        master.vm.hostname = "ahorsS"

        master.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = "1"
            vb.name = "ahorsS"
        end

        master.vm.provision "shell", inline: <<-SHELL
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install ansible==8.7.0
        SHELL
      
        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "install-k3s.yml"
            ansible.inventory_path = "inventory.ini"
        end

        # Copier les fichiers apps.yaml et ingress.yaml depuis l'hôte vers la VM
        master.vm.provision "file", source: "apps.yaml", destination: "/home/vagrant/apps.yaml"
        master.vm.provision "file", source: "ingress.yaml", destination: "/home/vagrant/ingress.yaml"
        
        master.vm.provision "shell", inline: <<-SHELL
          sudo mv /home/vagrant/apps.yaml /var/lib/rancher/k3s/server/manifests/
          sudo mv /home/vagrant/ingress.yaml /var/lib/rancher/k3s/server/manifests/
        SHELL

        # Déplacer les fichiers dans le dossier manifests K3s et attendre que les pods soient Running
        master.vm.provision "shell", inline: <<-SHELL
          sudo mv /home/vagrant/apps.yaml /var/lib/rancher/k3s/server/manifests/
          sudo mv /home/vagrant/ingress.yaml /var/lib/rancher/k3s/server/manifests/

          echo "Attente que tous les pods soient Running..."
          until sudo kubectl get pods -A --no-headers | grep -v Running | grep -v Completed | wc -l | grep -q '^0$'; do
            echo "Pods pas encore tous Running, attente 5s..."
            sleep 5
          done
          echo "Tous les pods sont Running!"
        SHELL

    end
end
