Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Server node
  config.vm.define "ebaillotS" do |server|
    server.vm.hostname = "ebaillotS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    server.vm.synced_folder "./shared", "/vagrant/shared"

    server.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y build-essential linux-headers-$(uname -r)
    SHELL
    server.vm.provision "shell", path: "scripts/install_k3s_server.sh"
  end

  # Agent node
  config.vm.define "ebaillotSW" do |agent|
    agent.vm.hostname = "ebaillotSW"
    agent.vm.network "private_network", ip: "192.168.56.111"
    agent.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    agent.vm.synced_folder "./shared", "/vagrant/shared"

    agent.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y build-essential linux-headers-$(uname -r) netcat
    SHELL
    agent.vm.provision "shell", path: "scripts/install_k3s_agent.sh"
  end
end