Vagrant.configure("2") do |config|
  # Define the server node
  config.vm.define "ebaillotS" do |server|
    server.vm.box = "ubuntu/bionic64"
    server.vm.hostname = "ebaillotS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    # VM resources
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    # Provision the server node
    server.vm.provision "shell", path: "scripts/install_k3s_server.sh"
  end

  # Define the worker node
  config.vm.define "ebaillotSW" do |worker|
    worker.vm.box = "ubuntu/bionic64"
    worker.vm.hostname = "ebaillotSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    
    # VM resources
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    # Provision the worker node
    worker.vm.provision "shell", path: "scripts/install_k3s_worker.sh"
  end
end